In [25]:
%matplotlib inline

import neurolab as nl
import numpy as np
import matplotlib.pylab as pl
import math

pl.style.use('ggplot')
pl.rcParams["figure.figsize"] = [12, 9]

In [26]:
def Norma(v):
    norma_v = 0
    for i in range(len(v)):
        norma_v += v[i]*v[i]

    return math.sqrt(norma_v)

In [27]:
n = 4

x = np.array([[2., -1., 0., 0.], [1., 2., 0., 0.], [0., 0., 2., 1.], [0., 0., 1., -2.]])

for i in range(len(x)):
    x[i] = x[i]/Norma(x[i])
    
    
print(x)

d = np.array([[1, 1], [-1, -1], [1, -1], [-1, 1]])

[[ 0.89442719 -0.4472136   0.          0.        ]
 [ 0.4472136   0.89442719  0.          0.        ]
 [ 0.          0.          0.89442719  0.4472136 ]
 [ 0.          0.          0.4472136  -0.89442719]]


In [29]:
net = nl.net.newp(nl.tool.minmax(x), 2, nl.net.trans.PureLin())

w = np.zeros((2,4))

for i in range(4):
    for j in range(2):
        for k in range (n):
            w[j,i] += x[k,i]*d[k,j]
            
        

net.layers[0].np['w'] = w
net.layers[0].np['b'] = 0
# error = net.train(x, d, epochs=1000, show=100, goal=0.02)

y = net.sim(x)

print("Training data")
print(x)
print(y.round(0))
print("Delta")
print(d-y)

xtest = x + np.eye(4)

for i in range(len(xtest)):
    xtest[i] = xtest[i]/Norma(xtest[i])

y = net.sim(xtest)

print("Test input")
print(xtest)
print(y.round(0))
print("Delta")
print(d-y)

xtest = x + np.array([[1., 0., 1. ,1.], [0., 0., 1., 0.], [0., 1., 0., 0.], [1., 0., 0., 0.]])

for i in range(len(xtest)):
    xtest[i] = xtest[i]/Norma(xtest[i])

y = net.sim(xtest)

print("Shifted test input")
print(xtest)
print(y.round(0))
print("Delta")
print(d-y)

Training data
[[ 0.89442719 -0.4472136   0.          0.        ]
 [ 0.4472136   0.89442719  0.          0.        ]
 [ 0.          0.          0.89442719  0.4472136 ]
 [ 0.          0.          0.4472136  -0.89442719]]
[[ 1.  1.]
 [-1. -1.]
 [ 1. -1.]
 [-1.  1.]]
Delta
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
Test input
[[ 0.97324899 -0.22975292  0.          0.        ]
 [ 0.22975292  0.97324899  0.          0.        ]
 [ 0.          0.          0.97324899  0.22975292]
 [ 0.          0.          0.97324899  0.22975292]]
[[ 1.  1.]
 [-1. -1.]
 [ 1. -1.]
 [ 1. -1.]]
Delta
[[ 0.25650393  0.25650393]
 [ 0.20300191  0.20300191]
 [ 0.25650393 -0.25650393]
 [-1.74349607  1.74349607]]
Shifted test input
[[ 0.78737497 -0.18587402  0.41562694  0.41562694]
 [ 0.31622777  0.63245553  0.70710678  0.        ]
 [ 0.          0.70710678  0.63245553  0.31622777]
 [ 0.70710678  0.          0.31622777 -0.63245553]]
[[ 1. -0.]
 [-0. -1.]
 [-0. -2.]
 [-0.  1.]]
Delta
[[-0.34499702  1.14199511]
 [-0.60